apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-apache
  name: my-apache
  namespace: reddy-ns
spec:
  ports:
  - name: ssh
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-apache
  type: LoadBalancer