apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: my-apache
  namespace: reddy-ns
spec:
  selector:
    matchLabels:
      app: my-apache
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: my-apache
    spec:
      containers:
      - name: apache
        image: nginx:1.14.2
        ports:
        - containerPort: 80
