apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-apache
  name: my-apache
  namespace: my-apache
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: my-apache
  type: LoadBalancer